### ISSUE TITLE
MACOS找不到温州话选项

### ISSUE THREAD

**Issue by shadowhalo** [ZWolken/rime-wenzhounese#2]
### 疑問/問題描述

安装好鼠须管，yaml文件都拷进Rime文件后，ctrl+·没有温州话的方案可以选。

### 注意事项

- [X] 我已知晓该仓库所有者僅會在能力範圍内進行問題進行解答，能力範圍以外的將無法解答。

**Comment by ZWolken** [comment]
请问您是根据我提供给Windows系统的步骤进行操作的吗？Windows系统的安装步骤不适用macOS，您可以在网络上搜索参考鼠须管的安装配置教程进行安装。

比如我找到的一个[教程](https://ngli.github.io/%E5%AE%89%E8%A3%85%E6%96%B9%E6%B3%95/macOS.html)，在将全部文件放到Rime的用户文件夹（`~/Library/Rime/`，可以通过点击输入法状态栏上的Rime图标，选择“用户设定...”来打开）后，需要手动修改该目录下的`default.custom.yaml`文件，加入
```yaml
- schema: wenzhounese
```

然后输入法状态栏上点击“重新部署”，等待一段时间后应该就可以通过按下<kbd>Ctrl</kbd>+<kbd>｀</kbd> 或 <kbd>F4</kbd>，从选单中选择温州话输入方案了。

**Comment by shadowhalo** [comment]
不是按win教程，是拷到～/library/rime/下的，没有找到default.custom.yaml这个文件啊

**Comment by ZWolken** [comment]
如果不存在该文件的话需要自行创建。
文件内完整内容如下：
```yaml
patch:
schema_list:
    - schema: wenzhounese
```

保存后再重新部署试试？

**Comment by shadowhalo** [comment]
新建了，重新部署了，重启了，还是沒有。。。〔方案選單〕

**Comment by ZWolken** [comment]
那就暂时没办法了，我手头没有macOS系统的电脑，无法调试测试，属实抱歉。

**Comment by shadowhalo** [comment]
用你發渠鏈接裏渠下載落有default，行着罷，謝謝。
